server:
  applicationContextPath: /booklibrary
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: 8082

authentication:
  tokenSecret: npoWdF1FaztS7jCsj0DRqGxF5obi3SuW

keycloakConfiguration:
  realm: bshevRealm
  auth-server-url: http://hello:8080/
  ssl-required: external
  resource: resource-server
  verify-token-audience: false
  credentials:
    secret: npoWdF1FaztS7jCsj0DRqGxF5obi3SuW
  confidential-port: 0